//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProject.AutoCode
{
    using System;
    using System.Collections.Generic;
    
    public partial class adminuser
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public System.DateTime AddTime { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<long> DeptId { get; set; }
        public string RealName { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> SocOrgId { get; set; }
    }
}
