//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProject.AutoCode
{
    using System;
    using System.Collections.Generic;
    
    public partial class department
    {
        public long Id { get; set; }
        public long PId { get; set; }
        public string Name { get; set; }
        public System.DateTime AddTime { get; set; }
        public Nullable<int> State { get; set; }
        public string Desc { get; set; }
        public Nullable<int> Level { get; set; }
    }
}
