//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProject.AutoCode
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu
    {
        public int id { get; set; }
        public Nullable<int> pId { get; set; }
        public string name { get; set; }
        public string file { get; set; }
        public Nullable<bool> open { get; set; }
        public string Module { get; set; }
        public string AText { get; set; }
    }
}
