//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProject.AutoCode
{
    using System;
    using System.Collections.Generic;
    
    public partial class serrecord
    {
        public int Id { get; set; }
        public string No { get; set; }
        public Nullable<int> SDId { get; set; }
        public Nullable<int> SocOrgId { get; set; }
        public string VId { get; set; }
        public Nullable<System.DateTime> BeginTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string Img { get; set; }
        public string Pos { get; set; }
        public string SerId { get; set; }
        public string City { get; set; }
        public string SocID { get; set; }
        public Nullable<int> Socre { get; set; }
        public string Comment { get; set; }
        public System.DateTime AddTime { get; set; }
        public string Source { get; set; }
    }
}
