//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProject.AutoCode
{
    using System;
    using System.Collections.Generic;
    
    public partial class socialorg
    {
        public int Id { get; set; }
        public Nullable<int> PId { get; set; }
        public Nullable<int> DepId { get; set; }
        public string Type { get; set; }
        public string SocialNO { get; set; }
        public string Name { get; set; }
        public string RegNO { get; set; }
        public string RegType { get; set; }
        public string OrgNo { get; set; }
        public string BusDesc { get; set; }
        public Nullable<System.DateTime> RegTime { get; set; }
        public Nullable<System.DateTime> EffectiveTime { get; set; }
        public Nullable<int> State { get; set; }
        public System.DateTime AddTime { get; set; }
        public string AddUser { get; set; }
    }
}
