//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProject.AutoCode
{
    using System;
    using System.Collections.Generic;
    
    public partial class socservicedetail
    {
        public int Id { get; set; }
        public string SerNum { get; set; }
        public string Type { get; set; }
        public string SocialNo { get; set; }
        public string Context { get; set; }
        public Nullable<System.DateTime> PubTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string Desc { get; set; }
        public string VHelpDesc { get; set; }
        public string CoverCommunity { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<int> THSScore { get; set; }
        public string Phone { get; set; }
        public string Contacts { get; set; }
        public System.DateTime AddTime { get; set; }
        public string AddUser { get; set; }
        public string PayType { get; set; }
    }
}
