//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProject.AutoCode
{
    using System;
    using System.Collections.Generic;
    
    public partial class volunteer
    {
        public int Id { get; set; }
        public string Number { get; set; }
        public string Type { get; set; }
        public Nullable<int> DepId { get; set; }
        public string Address { get; set; }
        public Nullable<int> RealNameState { get; set; }
        public string RealName { get; set; }
        public string CardType { get; set; }
        public string CardNum { get; set; }
        public string UerName { get; set; }
        public Nullable<int> Honor { get; set; }
        public string Phone { get; set; }
        public string EMail { get; set; }
        public string QQ { get; set; }
        public string WeiXin { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<int> ThsScore { get; set; }
        public Nullable<int> Score { get; set; }
        public string VID { get; set; }
        public string SocialNO { get; set; }
        public Nullable<int> State { get; set; }
        public string Msg { get; set; }
        public string PassWord { get; set; }
        public Nullable<int> Doing { get; set; }
        public System.DateTime AddTime { get; set; }
    }
}
